mybatis-plus:
  configuration:
    # 控制台日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mappers/*.xml
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false