management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  boot:
    admin:
      client:
        url: http://192.168.1.254:8025
        instance:
          prefer-ip: true
  application:
    name: actouator-test

# spring actuator
info:
  name: hello
  version: @project.version@

logging:
  file:
    path: d:/temp/